apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: postgresql
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg==  # base64 encoded "postgresadmin"
  POSTGRES_PASSWORD: YWRtaW4xMjM=       # base64 encoded "admin123"
  POSTGRES_DB: cG9zdGdyZXNkYg==         # base64 encoded "postgresdb"
  REPLICATION_USER: cmVwbGljYXRpb251c2Vy  # base64 encoded "replicationuser"
  REPLICATION_PASSWORD: cmVwbGljYXRpb25QYXNzd29yZA==  # base64 encoded "replicationPassword"
